# To use this file:
# Rename this file to wrangler.toml.
# If using wrangler.toml, you must treat your wrangler.toml as the source of truth for
# CloudFlare Pages project configuration when deploying to CloudFlare.
# Any misconfiguration (e.g. a R2 / KV binding resource doesn't exist in CloudFlare account)
# will make CloudFlare pages throw a building error:
#   "Error: Failed to publish your Function. Got error: Unknown internal error occurred."
# Start local dev environment:
#   npm i
#   npm run build
#   npm start
# It's using Wrangler: https://developers.cloudflare.com/workers/wrangler/
# wrangler.toml: https://developers.cloudflare.com/workers/wrangler/configuration/
compatibility_date = "2024-12-03"
name = "flaredrive"
pages_build_output_dir = "dist"


# Environment Variables are available only in the build phase of the website.
# Any changes need re-deploy (re-build) to make effect.
# Note: in local dev mode, the below front side env could be overridden by ".env.local":
#   SITENAME
# It will copy ".env.local" to ".dev.vars" file when vite starts, as wrangler only recognize the latter.
# See https://github.com/cloudflare/workers-sdk/issues/3106 .
[vars]
WEBDAV_USERNAME = "root"
WEBDAV_PASSWORD = "pass"
# comma separated prefixes, files which key starts with any of these prefixes can be publicly accessed (read)
# E.g. "http://127.0.0.1:8788/dav/public/foo.png"
PUBLIC_PREFIX = "public_files"
# Similar to PUBLIC_PREFIX.
# Additionally, pathes of these prefixs allow publicly dir browsing
PUBLIC_DIR_PREFIX = "public"
SITENAME = "MyDrive"
SHORT_SITENAME = "Drive"

# Change bucket_name to the real one
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "bucket"

# Bind cloudflare KV
# https://developers.cloudflare.com/kv/api/read-key-value-pairs/
[[kv_namespaces]]
binding = "KV"
id = "kv_id"
