compatibility_date = "2025-04-01"
name = "flaredrive"
# Note: "./index.js" depends on "./dist_worker/index.js",
# the latter is compiled at build time by "npm run build:worker".
main = "./index.js"
keep_vars = true

# https://developers.cloudflare.com/workers/configuration/compatibility-flags/#navigation-requests-prefer-asset-serving
compatibility_flags = ["assets_navigation_has_no_effect"]

# This file "wrangler.example.toml" is intended to be used in local development env.
# 1. Copy this file to wrangler.toml.
# 2. Run "npm run build:worker" to build worker.
# 3. Run "npm run cfdev" to start wrangler dev (backend) server.
# Each time the backend source files (functions/*, lib/*) changed, run "npm run build:worker" again.

# In production env, it dynamically generate wrangler.json from wrangler.example.json at build time
# Fill the bindings info from (build time) "Variables and secrets".
#r2_buckets = [{ binding = "BUCKET", bucket_name = "" }]
#kv_namespaces = [{ binding = "KV", id = "" }]
#d1_databases = [{ binding = "DB", database_name = "flaredrive", database_id = "" }]

r2_buckets = [{ binding = "BUCKET", bucket_name = "bucket" }]
kv_namespaces = [{ binding = "KV", id = "kv" }]
d1_databases = [
  { binding = "DB", database_name = "flaredrive", database_id = "db" },
]

[[durable_objects.bindings]]
name = "REINDEXER_DO"
class_name = "ReindexerDO"

# A migration is a mapping process from a class name to a runtime state.
# You perform a migration when creating a new Durable Object class,
# or when renaming, deleting or transferring an existing Durable Object class.
# See: https://developers.cloudflare.com/durable-objects/get-started/ ,
# https://developers.cloudflare.com/durable-objects/reference/durable-objects-migrations/ .
# Migrations are not necessary in dev environment.
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReindexerDO"]


[images]
binding = "IMAGES"

[assets]
# vite build
directory = "./dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"

[triggers]
# To test in "wrangler dev --test-scheduled" environment:
#  curl "http://localhost:8787/__scheduled"
crons = ["30 * * * *"]
